/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export interface KingInterface extends utils.Interface {
  functions: {
    "MATIC_USD_ORACLE()": FunctionFragment;
    "USDC_ADDRESS()": FunctionFragment;
    "_king()": FunctionFragment;
    "deposit(uint256)": FunctionFragment;
    "getLatestPrice(address)": FunctionFragment;
    "previous_maximum()": FunctionFragment;
    "previous_usdc_maximum()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "MATIC_USD_ORACLE"
      | "USDC_ADDRESS"
      | "_king"
      | "deposit"
      | "getLatestPrice"
      | "previous_maximum"
      | "previous_usdc_maximum"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "MATIC_USD_ORACLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "USDC_ADDRESS",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "_king", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "deposit",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getLatestPrice",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "previous_maximum",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "previous_usdc_maximum",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "MATIC_USD_ORACLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "USDC_ADDRESS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "_king", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getLatestPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "previous_maximum",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "previous_usdc_maximum",
    data: BytesLike
  ): Result;

  events: {};
}

export interface King extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: KingInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    MATIC_USD_ORACLE(overrides?: CallOverrides): Promise<[string]>;

    USDC_ADDRESS(overrides?: CallOverrides): Promise<[string]>;

    _king(overrides?: CallOverrides): Promise<[string]>;

    deposit(
      deposit_amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    getLatestPrice(
      _oracle_address: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    previous_maximum(overrides?: CallOverrides): Promise<[BigNumber]>;

    previous_usdc_maximum(overrides?: CallOverrides): Promise<[BigNumber]>;
  };

  MATIC_USD_ORACLE(overrides?: CallOverrides): Promise<string>;

  USDC_ADDRESS(overrides?: CallOverrides): Promise<string>;

  _king(overrides?: CallOverrides): Promise<string>;

  deposit(
    deposit_amount: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  getLatestPrice(
    _oracle_address: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  previous_maximum(overrides?: CallOverrides): Promise<BigNumber>;

  previous_usdc_maximum(overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    MATIC_USD_ORACLE(overrides?: CallOverrides): Promise<string>;

    USDC_ADDRESS(overrides?: CallOverrides): Promise<string>;

    _king(overrides?: CallOverrides): Promise<string>;

    deposit(
      deposit_amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    getLatestPrice(
      _oracle_address: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    previous_maximum(overrides?: CallOverrides): Promise<BigNumber>;

    previous_usdc_maximum(overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    MATIC_USD_ORACLE(overrides?: CallOverrides): Promise<BigNumber>;

    USDC_ADDRESS(overrides?: CallOverrides): Promise<BigNumber>;

    _king(overrides?: CallOverrides): Promise<BigNumber>;

    deposit(
      deposit_amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    getLatestPrice(
      _oracle_address: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    previous_maximum(overrides?: CallOverrides): Promise<BigNumber>;

    previous_usdc_maximum(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    MATIC_USD_ORACLE(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    USDC_ADDRESS(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    _king(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    deposit(
      deposit_amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    getLatestPrice(
      _oracle_address: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    previous_maximum(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    previous_usdc_maximum(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
