/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { King__factory } from "./King__factory";
export { Migrations__factory } from "./Migrations__factory";
