/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../common";
import type {
  Migrations,
  MigrationsInterface,
} from "../../contracts/Migrations";

const _abi = [
  {
    inputs: [],
    name: "last_completed_migration",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "completed",
        type: "uint256",
      },
    ],
    name: "setCompleted",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

const _bytecode =
  "0x6080604052341561000f57600080fd5b600080546001600160a01b0319163317905561023680610031608039806080f3fe6080604052600436106100d7576000803560e01c63445df0ac811461003957638da5cb5b811461007a5763fdacd57681146100b3576100d4565b3415610043578182fd5b61004c366100dc565b6001546080527fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff8060a0016080f35b3415610084578182fd5b61008d366100dc565b815460405173ffffffffffffffffffffffffffffffffffffffff90911680825290602081f35b34156100bd578182fd5b6100ce6100c93661010f565b610149565b81604051f35b50505b600080fd5b60007ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffc8201121561010c57600080fd5b50565b600060207ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffc8301121561014157600080fd5b505060043590565b73ffffffffffffffffffffffffffffffffffffffff6000541633146101ed576040517f08c379a000000000000000000000000000000000000000000000000000000000815260206004820152603360248201527f546869732066756e6374696f6e206973207265737472696374656420746f207460448201527f686520636f6e74726163742773206f776e6572000000000000000000000000006064820152608481fd5b60015556fea3646970667358221220edb24af1c5c08a5f7acd7524f98e610a6006595d80a3ff4bcfdfa2aa58a4b9e46c6578706572696d656e74616cf564736f6c63430008070041";

type MigrationsConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: MigrationsConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class Migrations__factory extends ContractFactory {
  constructor(...args: MigrationsConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<Migrations> {
    return super.deploy(overrides || {}) as Promise<Migrations>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): Migrations {
    return super.attach(address) as Migrations;
  }
  override connect(signer: Signer): Migrations__factory {
    return super.connect(signer) as Migrations__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): MigrationsInterface {
    return new utils.Interface(_abi) as MigrationsInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): Migrations {
    return new Contract(address, _abi, signerOrProvider) as Migrations;
  }
}
